# The query returns average pollutants concentration in a time interval grouped by source
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aq: <http://www.semanticweb.org/saadf/ontologies/2021/2/AirQualityOntology#>
PREFIX saqi: <https://kracr.iiitd.edu.in/ontology/saqi#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT  ?pm_10 ?pm_25 ?placeName ?hasliteracy ?countLiteracy{
  {
    SELECT (AVG(?pm10Instance) AS ?pm_10) (AVG(?pm25Instance) AS ?pm_25) ?placeName ?source WHERE {
      ?pm a saqi:ParticulateMatter;	
      saqi:particulateMatter10Concentration ?pm10Instance ;
      saqi:particulateMatter2_5Concentration ?pm25Instance .
      
      ?pm saqi:hasObservation ?obs .
      ?obs saqi:atTime ?time ;
      saqi:atPlace ?place ;
      saqi:dataSource ?source .
      ?place saqi:hasName ?placeName .
      
      # Add location name or time interval filter
    #  FILTER (
    #    ?placeName="ShaheenBagh"^^rdfs:Literal
    #  	?time > "2021-11-01T00:00:00+05:30"^^xsd:dateTime
    #    ?time < "2021-11-10T00:00:00+05:30"^^xsd:dateTime
#      )
    } 
    GROUP BY ?source ?placeName
    LIMIT 10000
  }
  {
    SELECT ?hasliteracy ?placeName (COUNT( ?hasliteracy) as ?countLiteracy) WHERE {
      ?person rdf:type saqi:Person ;
      saqi:hasIndividualPerception ?perception ;
      saqi:isPartOfSocialCohort ?cohort ;
      saqi:livesIn ?place ;
      saqi:hasAirPollutionLiteracy ?literacy .
      ?perception saqi:localAirQualityRating ?rating .
      ?literacy saqi:hasAQILiteracy ?hasliteracy .

      ?place saqi:hasName ?placeName .

    } 
    GROUP BY ?hasliteracy ?placeName
    ORDER BY ?hasliteracy ?placeName
  }

}
ORDER BY ?placeName ?hasliteracy